# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JWSRxSwiftBeginningSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JWSRxSwiftBeginningSample

  # Core
  pod 'RxSwift'
  pod 'RxCocoa'

  # Network
  pod 'RxAlamofire'

end
